### ISSUE TITLE
It seems that current published version 0.0.3 is older than the source code here

### ISSUE THREAD

**Issue by tobiasweibel** [antsmartian/preact-testing-library#17]
* `react-testing-library` version: 0.0.3
* `node` version: 10.15.3
* `yarn` version: 1.15.2

Relevant code (example from readme):

```javascript
import {render} from 'preact-testing-library'

const {rerender} = render(<NumberDisplay number={1} />)

// re-render the same component with different props
rerender(<NumberDisplay number={2} />)
```

Problem description:
I basically wanted to use the `rerender` method but it's `undefined`. Then I digged into the dist/index.js file and it looks for me that that compiled code is basically before #4 was merged. Also other `render()` return values are mssing. Since version 0.0.3 was released after #4 I guess that this version was somehow built with old code in dist repository.

Suggested solution:
Republish latest code with a new version.

**Comment by philippkast** [comment]
Would be nice to get that fixed!

**Comment by molefrog** [comment]
Confirming this, the current published version 0.3.0 does not contain `debug` method for example.

**Comment by antsmartian** [comment]
Oops, I'm sorry for this.. Not sure how I have missed it. Anyways, have updated to version `0.4.0` along with https://github.com/antsmartian/preact-testing-library/pull/16, https://github.com/antsmartian/preact-testing-library/pull/15. Can confirm by `dist/index.js` has methods like `debug`, `unmount`, `rerender`

**Comment by antsmartian** [comment]
@molefrog @tobiasweibel @philippkast Ping 🔉 Will close it, once you guys can confirm.

**Comment by tobiasweibel** [comment]
@antsmartian version 0.4.0 fixes the problem. Thanks!

**Comment by antsmartian** [comment]
Closing this issue.. Thanks everyone for reporting this!

**Comment by molefrog** [comment]
Just updated the package, everything seems to work now. Thanks @antsmartian
