### ISSUE TITLE
Missing TypeScript declarations

### ISSUE THREAD

**Issue by goblindegook** [antsmartian/preact-testing-library#5]
The project is missing up-to-date TypeScript declarations for the `cleanup`, `debounceRenderingOff`, and `flushPromises` functions as well as all the dependencies inherited from `dom-testing-library` (like `fireEvent` and so forth).

**Comment by antsmartian** [comment]
@goblindegook Yes, I need to work on updating the library and move to `dom-testing-library` etc. Not getting enough time.

**Comment by goblindegook** [comment]
Resolved by #6.

**Comment by antsmartian** [comment]
Thanks @goblindegook . Please add yourself in contributors list.
