### ISSUE TITLE
"SecurityError: localStorage is not available for opaque origins" when testing

### ISSUE THREAD

**Issue by goblindegook** [antsmartian/preact-testing-library#7]
Newer versions of `jsdom` will throw a "SecurityError: localStorage is not available for opaque origins" error unless a test URL is provided.

```
 FAIL  src/__tests__/preact-redux.js
  ● Test suite failed to run
    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)
```

I don't know how to get around it using this project's stack. If using `jsdom` through Jest, this is the fix: https://github.com/facebook/jest/issues/6766#issuecomment-408344243

**Comment by antsmartian** [comment]
Hello, thanks for informing me this. I have fixed it by enforcing the `jsdom` to use the older version. See: https://github.com/antsmartian/preact-testing-library/commit/a866515a003828f62e0a3e490e7ef28244e26d21
