### ISSUE TITLE
Release 0.2.0 does not have a dist directory

### ISSUE THREAD

**Issue by goblindegook** [antsmartian/preact-testing-library#8]
Freshly installed using NPM and Yarn, version 0.2.0 of the package does not include the `dist` directory. Also, the typings directory (which is included) does not have the latest version of the `index.d.ts` file.

**Comment by antsmartian** [comment]
@goblindegook Thanks a ton, somehow my script didn't run `build` before publish. I have republished the module along with updated `index.d.ts` file. Can you try `0.2.1`? 

Also feel free to add yourself in : https://github.com/antsmartian/preact-testing-library/blob/master/.all-contributorsrc

Once you see right files coming up, I guess you can close the issue.

**Comment by goblindegook** [comment]
Looks good, thanks!
